name: emansur_logger
description: A simple message decorator that uses emojis to wrap around the message.
version: 0.0.1+1
homepage: https://github.com/ebrahimmansur/my_custom_flutter_packages/tree/main/emansur_logger

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  